// redux/store/chefsApi.js
import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

export const chefsApi = createApi({
  reducerPath: "chefsApi", // The reducer path for this API
  baseQuery: fetchBaseQuery({ baseUrl: "http://localhost:5000/api/user" }), // Base URL for the API
  endpoints: (builder) => ({
    getChefs: builder.query({
      query: (userId) => `get-all-users/${userId}`, // API endpoint
    }),
    toggleFollow: builder.mutation({
      query: ({ followerId, followingId }) => ({
        url: "toggle-follow", // Endpoint for toggling follow
        method: "POST",
        body: { followerId, followingId }, // Request payload
      }),
    }),
  }),
});

// Export hooks generated by RTK Query
export const { useGetChefsQuery, useToggleFollowMutation } = chefsApi;
