// redux/store/likesApi.js
import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

export const likesApi = createApi({
  reducerPath: "likesApi", // The reducer path for this API
  baseQuery: fetchBaseQuery({ baseUrl: `${process.env.REACT_APP_BACKEND_URL}/api/like` }), // Base URL for the API
  tagTypes: ["Likes"], // Define tag types for invalidation
  endpoints: (builder) => ({
    getLikes: builder.query({
      query: (recipeId,userId) => `get-likes/${recipeId}/${userId}`, // Endpoint to fetch likes for a recipe
      providesTags: ["Likes"], // Tags data with a generic "Likes" tag
    }),
    toggleLike: builder.mutation({
      query: ({ userId, recipeId }) => ({
        url: "toggle-like", // Endpoint for toggling like
        method: "POST",
        body: { userId, recipeId }, // Request payload
      }),
      invalidatesTags: ["Likes"], // Invalidates "Likes" tag to refetch the likes data
    }),
  }),
});

// Export hooks generated by RTK Query
export const { useGetLikesQuery, useToggleLikeMutation } = likesApi;
